# Generated by Django 3.0.3 on 2020-04-22 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0002_auto_20200423_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Bio',
            field=models.TextField(null=True),
        ),
    ]
