# Generated by Django 3.0.3 on 2020-04-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0005_auto_20200426_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Cover_Image',
            field=models.ImageField(default='users_profiles/cover_images/default_cover_image.jpg', upload_to='users_profiles/cover_images'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Profile_Image',
            field=models.ImageField(default='users_profiles/profile_images/default_profile_image.jpg', upload_to='users_profiles/profile_images/'),
        ),
    ]
