# Generated by Django 3.0.3 on 2020-04-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0006_auto_20200426_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='First_Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile_model',
            name='Last_Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='profile_model',
            name='User_Name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Address',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Job',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
