# Generated by Django 3.0.3 on 2020-04-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0007_auto_20200428_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Cover_Image',
            field=models.ImageField(default='default_images/default_cover_image.jpg', upload_to='users_profiles/<django.db.models.fields.CharField>/cover_images/'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Profile_Image',
            field=models.ImageField(default='default_images/default_profile_image.jpg', upload_to='users_profiles/<django.db.models.fields.CharField>/profile_images/'),
        ),
        migrations.AlterField(
            model_name='sharing_image',
            name='Image',
            field=models.ImageField(upload_to='users_profiles/<django.db.models.fields.related.ForeignKey>/uploads_images/'),
        ),
    ]
