# Generated by Django 3.0.3 on 2020-04-30 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0008_auto_20200430_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing_image',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='sharing_image',
            name='Image_Date',
        ),
        migrations.RemoveField(
            model_name='sharing_image',
            name='Image_Text',
        ),
        migrations.RemoveField(
            model_name='sharing_image',
            name='username',
        ),
    ]
