# Generated by Django 3.0.3 on 2020-04-30 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Account', '0009_auto_20200430_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing_image',
            name='Image',
            field=models.ImageField(null=True, upload_to='users_profiles/<django.db.models.fields.CharField>/uploads_images/'),
        ),
        migrations.AddField(
            model_name='sharing_image',
            name='Image_Date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sharing_image',
            name='Image_Text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sharing_image',
            name='Upload_Path',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='sharing_image',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
