# Generated by Django 3.0.3 on 2020-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0011_auto_20200430_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing_image',
            name='Image',
            field=models.ImageField(null=True, upload_to='users_profiles/uploads_images/'),
        ),
    ]
