# Generated by Django 3.0.3 on 2020-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0012_auto_20200430_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Cover_Image',
            field=models.ImageField(default='users_profiles/default_cover_image.jpg', upload_to='users_profiles/cover_images/'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Profile_Image',
            field=models.ImageField(default='users_profiles/default_profile_image.jpg', upload_to='users_profiles/profile_images/'),
        ),
    ]
