# Generated by Django 3.0.6 on 2020-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0013_auto_20200501_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Cover_Image',
            field=models.ImageField(default='users_profiles/covers_images/default_cover_image.jpg', upload_to='users_profiles/cover_images/'),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Profile_Image',
            field=models.ImageField(default='users_profiles/profiles_images/default_profile_image.jpg', upload_to='users_profiles/profile_images/'),
        ),
    ]
