# Generated by Django 3.0.6 on 2020-06-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0014_auto_20200609_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharing_post',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharing_post',
            name='Loves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharing_post',
            name='Shares',
            field=models.IntegerField(default=0),
        ),
    ]
