# Generated by Django 3.0.6 on 2020-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0016_auto_20200611_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharing_image',
            name='Image_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sharing_post',
            name='Post_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
