# Generated by Django 3.0.6 on 2020-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0018_auto_20200612_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Bio',
            field=models.TextField(default='BIO', max_length=80),
        ),
    ]
