# Generated by Django 3.0.6 on 2020-06-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0020_auto_20200616_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing_image',
            name='Shares',
        ),
    ]
