# Generated by Django 3.0.6 on 2020-06-23 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Account', '0024_auto_20200622_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars_Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Star', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Star', to=settings.AUTH_USER_MODEL)),
                ('Vote', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification_Type', models.CharField(max_length=64)),
                ('Notification_Text', models.CharField(max_length=240)),
                ('Notification_Status', models.CharField(max_length=32)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Friend', models.BooleanField(default=False)),
                ('Follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Follower', to=settings.AUTH_USER_MODEL)),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
