# Generated by Django 3.0.6 on 2020-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0025_followers_notifications_stars_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_model',
            name='Editable',
            field=models.BooleanField(default=True),
        ),
    ]
