# Generated by Django 3.0.6 on 2020-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_Account', '0027_auto_20200708_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_model',
            name='Codepen_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Facebook_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Github_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Instagram_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Kaggle_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='LinkedIn_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Twitter_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='profile_model',
            name='Youtube_Link',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
