# Generated by Django 3.0.6 on 2020-06-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts_likes',
            name='Like_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts_loves',
            name='Love_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts_shares',
            name='Share_Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
