# Generated by Django 3.0.6 on 2020-06-12 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('My_Account', '0018_auto_20200612_1927'),
        ('Profiles', '0002_auto_20200612_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts_Likes',
            new_name='Posts_Amazing',
        ),
        migrations.RenameModel(
            old_name='Posts_Loves',
            new_name='Posts_Good',
        ),
        migrations.RenameField(
            model_name='posts_amazing',
            old_name='Like_Date',
            new_name='Amazing_Date',
        ),
        migrations.RenameField(
            model_name='posts_good',
            old_name='Love_Date',
            new_name='Good_Date',
        ),
    ]
